# Sécurité
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

# Page d'accueil
app_accueil:
  path: /accueil
  controller: App\Controller\AccueilController::index

# Redirection de / vers /accueil
homepage_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_accueil

# Guides touristiques
guide_index:
  path: /guide
  controller: App\Controller\GuideController::index

guide_new:
  path: /guide/new
  controller: App\Controller\GuideController::new

guide_show:
  path: /guide/{id}
  controller: App\Controller\GuideController::show

guide_edit:
  path: /guide/{id}/edit
  controller: App\Controller\GuideController::edit

guide_delete:
  path: /guide/{id}/delete
  controller: App\Controller\GuideController::Delete

# Visites
visite_index:
  path: /visite
  controller: App\Controller\VisiteController::index

visite_new:
  path: /visite/new
  controller: App\Controller\VisiteController::new

visite_show:
  path: /visite/{id}
  controller: App\Controller\VisiteController::show

visite_edit:
  path: /visite/{id}/edit
  controller: App\Controller\VisiteController::edit

visite_delete:
  path: /visite/{id}
  controller: App\Controller\VisiteController::delete
  methods: [POST]

# Visiteurs
visiteur_index:
  path: /visiteur
  controller: App\Controller\VisiteurController::index

visiteur_new:
  path: /visiteur/new/{id}
  controller: App\Controller\VisiteurController::new

visiteur_show:
  path: /visiteur/show/{id}
  controller: App\Controller\VisiteurController::show

visiteur_delete:
  path: /visiteur/{id}
  controller: App\Controller\VisiteurController::delete
  methods: [POST]

visiteur_new_selection_redirect:
  path: /visiteur/choisir-visite/redirection
  controller: App\Controller\VisiteurController::redirectToNew
  methods: [GET]

visiteur_new_selection:
  path: /visiteur/choisir-visite
  controller: App\Controller\VisiteurController::selectVisite
  methods: [GET]
# Utilisateurs
user_index:
  path: /user
  controller: App\Controller\UserController::index

user_new:
  path: /user/new
  controller: App\Controller\UserController::new

# Statistiques
stats_index:
  path: /admin/stats
  controller: App\Controller\StatistiquesController::index
