parameters:
  locale: 'fr'
  photos_directory: '%kernel.project_dir%/public/uploads/guides'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
